/*
       Licensed to the Apache Software Foundation (ASF) under one
       or more contributor license agreements.  See the NOTICE file
       distributed with this work for additional information
       regarding copyright ownership.  The ASF licenses this file
       to you under the Apache License, Version 2.0 (the
       "License"); you may not use this file except in compliance
       with the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing,
       software distributed under the License is distributed on an
       "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
       KIND, either express or implied.  See the License for the
       specific language governing permissions and limitations
       under the License.
 */

// Custom changes to fix the phonegap android fieldays innovation app's orientation to "landscape" for our Fieldays Innovation "Activity"
// It didn't help to change tipple-phonegap\phonegap-fieldays-innovation\platforms\android\AndroidManifest.xml
// or tipple-phonegap\phonegap-fieldays-innovation\platforms\android\ant-build\AndroidManifest.cordova.xml
// This manually-edited FieldaysInnovation.java Activity class, which may have been generated by Phonegap registering platforms, lives in 
// tipple-phonegap\phonegap-fieldays-innovation\platforms\android\src\nz\ac\waikato\cs\tipple\innovation2014\FieldaysInnovation.java
 
package nz.ac.waikato.cs.tipple.innovation2014;

import android.os.Bundle;
import org.apache.cordova.*;
import android.content.pm.ActivityInfo;

public class FieldaysInnovation extends CordovaActivity 
{
    @Override
    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
		
		// Fix to the very problem described in
		// http://stackoverflow.com/questions/23804983/phonegap-landscape-orientation-samsung-tab-3
		// which is that, even after editing AndroidManifest.xml and AndroidManifest.cordova.xml to 
		// use "Landscape" for the main (FieldaysInnovation) Activity, these xml files got overwritten
		// every time with "userLandscape" and most pages appeared on the screen in Portrait anyway.
		// Fix described in http://stackoverflow.com/questions/9801128/phonegap-forcing-landscape-orientation
		// "try this in your activity. Inside onCreate() and before setContentView."
		// keeps the screen orientation in Landscape mode		
		setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
		
		
        super.init();
        // Set by <content src="index.html" /> in config.xml
        super.loadUrl(Config.getStartUrl());
        //super.loadUrl("file:///android_asset/www/index.html");
    }
	
}

